apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-with-delay
spec: 
  containers:
  - image: kdsingh1984/kubia-liveness
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
